# Generated by Django 5.1 on 2024-08-23 02:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventActorsApp', '0004_city'),
    ]

    operations = [
        migrations.AddField(
            model_name='attender',
            name='city',
            field=models.ForeignKey(default=81, on_delete=django.db.models.deletion.CASCADE, to='eventActorsApp.city'),
            preserve_default=False,
        ),
    ]
